### ISSUE TITLE
php version

### ISSUE THREAD

**Issue by klibansky** [VoidVolker/MagickSlicer#4]
Could this converted to a php version?

**Comment by VoidVolker** [comment]
You can call this script on server via php.

```
<?php
echo exec('magick-slicer.sh foo.jpg');
?>
```

**Comment by klibansky** [comment]
Thanks for this tip.
Isn't enabling exec a huge security risk?

**Comment by VoidVolker** [comment]
Connecting to any other untrusted device (server, PC, phone, etc.) is already huge security risk =) You just need to configure you server to be secured. If some one want to hack - he will.
